### ISSUE TITLE
Configuration management of CC devices (tracking issue)

### ISSUE THREAD

**Issue by GetPsyched** [CharaChorder/nexus#96]
### Premise

This issue tries to unify a list of features that are to be done WRT configuring CC devices and is an RFC for how this should be implemented, if at all.

### TODO
- [ ] Implement functions for each serial API setting and pin it to a version of CCOS
- [ ] Allow configuring these settings at runtime
- [ ] Allow configuring these settings using a config file (JSON, etc.)
- [ ] Notify users if an existing setting has changed or a new one has been introduced (similar to DB version mismatch prompts)

### Notes
- This TODO is non-exhaustive and is only supposed to track features as they come and go.
- This issue doesn't yet track chord/layout management.
- As discussed with the team, this isn't planned to be implemented yet (in favour of the web device manager) so I'll maintain everything as draft PRs or simply keep the work in a fork separately until the time is right. I'm posting this issue to keep a spot where any comments on this are persisted for future references.
